// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCC-IAiDDfX42OZJ8QE1Ky3n2hz_A9LzF8',
    appId: '1:146054874882:web:d3417518eaf16a84bfe41b',
    messagingSenderId: '146054874882',
    projectId: 'smartlocker-df2cb',
    authDomain: 'smartlocker-df2cb.firebaseapp.com',
    storageBucket: 'smartlocker-df2cb.appspot.com',
    measurementId: 'G-B9W12GSY3C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCeQ24Ub1MXCE668JAfFY_TLhvz9-z4CkQ',
    appId: '1:146054874882:android:2ef1cc92fca2890fbfe41b',
    messagingSenderId: '146054874882',
    projectId: 'smartlocker-df2cb',
    storageBucket: 'smartlocker-df2cb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyq8e4iEo2wxAwtYg3fv0PDvE-Wn_7mck',
    appId: '1:146054874882:ios:6c2a785a94c371babfe41b',
    messagingSenderId: '146054874882',
    projectId: 'smartlocker-df2cb',
    storageBucket: 'smartlocker-df2cb.appspot.com',
    iosBundleId: 'com.example.smartlocker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAyq8e4iEo2wxAwtYg3fv0PDvE-Wn_7mck',
    appId: '1:146054874882:ios:6c2a785a94c371babfe41b',
    messagingSenderId: '146054874882',
    projectId: 'smartlocker-df2cb',
    storageBucket: 'smartlocker-df2cb.appspot.com',
    iosBundleId: 'com.example.smartlocker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCC-IAiDDfX42OZJ8QE1Ky3n2hz_A9LzF8',
    appId: '1:146054874882:web:3361e73888d0407fbfe41b',
    messagingSenderId: '146054874882',
    projectId: 'smartlocker-df2cb',
    authDomain: 'smartlocker-df2cb.firebaseapp.com',
    storageBucket: 'smartlocker-df2cb.appspot.com',
    measurementId: 'G-B9DTMW3WJT',
  );

}